"""Canonical reason codes for trading decisions and lifecycle events.

Keep this module dependency-free so it can be reused from scripts, paper mode,
sandbox executors, backtests, and reports.
"""

from __future__ import annotations

from enum import StrEnum


class ReasonCode(StrEnum):
    BUY_DAILY_SIGNAL = "BUY_DAILY_SIGNAL"
    BUY_NEWS_EVENT = "BUY_NEWS_EVENT"

    SKIP_LOW_PROBA = "SKIP_LOW_PROBA"
    SKIP_EXCLUDED_TICKER = "SKIP_EXCLUDED_TICKER"
    SKIP_ALREADY_POSITION = "SKIP_ALREADY_POSITION"
    SKIP_ACTIVE_ORDER = "SKIP_ACTIVE_ORDER"
    SKIP_MAX_POSITIONS = "SKIP_MAX_POSITIONS"
    SKIP_INSUFFICIENT_CASH = "SKIP_INSUFFICIENT_CASH"
    SKIP_LOW_LIQUIDITY = "SKIP_LOW_LIQUIDITY"
    SKIP_WIDE_SPREAD = "SKIP_WIDE_SPREAD"
    SKIP_STALE_PRICE = "SKIP_STALE_PRICE"
    SKIP_STALE_DATA = "SKIP_STALE_DATA"
    SKIP_CHASE_RISK = "SKIP_CHASE_RISK"
    SKIP_LOW_CONFIDENCE_NEWS = "SKIP_LOW_CONFIDENCE_NEWS"
    SKIP_LOW_SOURCE_RELIABILITY = "SKIP_LOW_SOURCE_RELIABILITY"
    SKIP_NEGATIVE_NEWS = "SKIP_NEGATIVE_NEWS"
    SKIP_MARKET_NOT_CONFIRMED = "SKIP_MARKET_NOT_CONFIRMED"
    SKIP_RISK_LIMIT = "SKIP_RISK_LIMIT"
    SKIP_SIZE_TOO_SMALL = "SKIP_SIZE_TOO_SMALL"

    SELL_TAKE_PROFIT = "SELL_TAKE_PROFIT"
    SELL_STOP_LOSS = "SELL_STOP_LOSS"
    SELL_TIME_EXIT = "SELL_TIME_EXIT"
    SELL_NEGATIVE_NEWS = "SELL_NEGATIVE_NEWS"
    HOLD_NO_EXIT_CONDITION = "HOLD_NO_EXIT_CONDITION"

    ERROR_TINVEST_API = "ERROR_TINVEST_API"
    ERROR_POSITION_RECONCILE = "ERROR_POSITION_RECONCILE"
    ERROR_CONFIG_INVALID = "ERROR_CONFIG_INVALID"
    ERROR_MODEL_MISSING = "ERROR_MODEL_MISSING"


def is_skip(reason_code: str | ReasonCode) -> bool:
    return str(reason_code).startswith("SKIP_")


def is_error(reason_code: str | ReasonCode) -> bool:
    return str(reason_code).startswith("ERROR_")
